USE [W_GnBD]
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON PJFAIRLN
REBUILD;
ALTER INDEX ALL ON PJFAIRPT
REBUILD;
ALTER INDEX ALL ON PJFAPSW
REBUILD;
ALTER INDEX ALL ON PJFBOOKG
REBUILD;
ALTER INDEX ALL ON PJFCITY
REBUILD;
ALTER INDEX ALL ON PJFCREW
REBUILD;
ALTER INDEX ALL ON PJFFLIGH
REBUILD;
ALTER INDEX ALL ON PJFMAINT
REBUILD;
ALTER INDEX ALL ON PJFMATE
REBUILD;
ALTER INDEX ALL ON PJFPERSO
REBUILD;
ALTER INDEX ALL ON PJFPILOT
REBUILD;
ALTER INDEX ALL ON PJFPLANE
REBUILD;
ALTER INDEX ALL ON PJFROUTE
REBUILD;
GO