
--ASYNCPROCESS | Ver.: 2501
UPDATE [ASYNCPROCESS]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
UPDATE [ASYNCPROCESS]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--ASYNCPROCESSARGUMENT | Ver.: 2501
UPDATE [ASYNCPROCESSARGUMENT]
SET [CODS_APR] = NULL
where [CODS_APR] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO
--ASYNCPROCESSATTACHMENTS | Ver.: 2501
UPDATE [ASYNCPROCESSATTACHMENTS]
SET [CODS_APR] = NULL
where [CODS_APR] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO
--USERAUTHORIZATION | Ver.: 2501
UPDATE [USERAUTHORIZATION]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--PJFAIRLN | Ver.: 2669
UPDATE [PJFAIRLN]
SET [CODCITY] = NULL
where [CODCITY] in (0);
UPDATE [PJFAIRLN]
SET [CODAIRHB] = NULL
where [CODAIRHB] in (0);
GO
--PJFAIRPT | Ver.: 2669
UPDATE [PJFAIRPT]
SET [CODCITY] = NULL
where [CODCITY] in (0);
GO
--PJFAPSW | Ver.: 2669
UPDATE [PJFAPSW]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
UPDATE [PJFAPSW]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--PJFBOOKG | Ver.: 2669
UPDATE [PJFBOOKG]
SET [FLIGHT] = NULL
where [FLIGHT] in (0);
UPDATE [PJFBOOKG]
SET [CODPASGR] = NULL
where [CODPASGR] in (0);
UPDATE [PJFBOOKG]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO
--PJFCREW | Ver.: 2669
UPDATE [PJFCREW]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO
--PJFFLIGH | Ver.: 2669
UPDATE [PJFFLIGH]
SET [CODPLANE] = NULL
where [CODPLANE] in (0);
UPDATE [PJFFLIGH]
SET [CODROUTE] = NULL
where [CODROUTE] in (0);
UPDATE [PJFFLIGH]
SET [CODSOURC] = NULL
where [CODSOURC] in (0);
UPDATE [PJFFLIGH]
SET [CODCREW] = NULL
where [CODCREW] in (0);
UPDATE [PJFFLIGH]
SET [CODPILOT] = NULL
where [CODPILOT] in (0);
UPDATE [PJFFLIGH]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO
--PJFMAINT | Ver.: 2669
UPDATE [PJFMAINT]
SET [CODPLANE] = NULL
where [CODPLANE] in (0);
UPDATE [PJFMAINT]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO
--PJFMATE | Ver.: 2669
UPDATE [PJFMATE]
SET [CODCREW] = NULL
where [CODCREW] in (0);
UPDATE [PJFMATE]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO
--PJFPILOT | Ver.: 2669
UPDATE [PJFPILOT]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO
--PJFPLANE | Ver.: 2669
UPDATE [PJFPLANE]
SET [AIRCR] = NULL
where [AIRCR] in (0);
UPDATE [PJFPLANE]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO
--PJFROUTE | Ver.: 2669
UPDATE [PJFROUTE]
SET [AIRDS] = NULL
where [AIRDS] in (0);
UPDATE [PJFROUTE]
SET [AIRSC] = NULL
where [AIRSC] in (0);
UPDATE [PJFROUTE]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO


